#!/bin/bash
#
# A git hook to make sure user.email exists before committing

EMAIL=$(git config user.email)
ORIGIN=$(git config remote.origin.url)

if [ "$EMAIL" = "not-configured" ]; then
    if [[ "$ORIGIN"  == *"github.com"* ]]; then
        git config user.email antoon.johansson@gmail.com
    elif [[ "$ORIGIN" == *"git.workplace.com"* ]]; then
        git config user.email anton.johansson@workspace.com
    else
        echo "Aborting commit because 'user.email' is missing. Run one of the following:"
        echo " git config user.email antoon.johansson@gmail.com"
        echo " git config user.email anton.johansson@workplace.com"
        exit 1
    fi
fi
