#!/bin/bash

argument=$1
if [ -z $1 ] ; then
    argument="."
fi

path1="$(realpath $argument)"
path2=$path1
path2="$(echo $path2 | sed -r 's/\/Stable\//\/Dev\//g')"
path2="$(echo $path2 | sed -r 's/\/Releases\/2.6\/2.6.x\//\/Main\//g')"

cd $path2
