#!/bin/bash

argument=$1
if [ -z $1 ] ; then
    argument="."
fi

path1="$(realpath $argument)"
path2=$path1
path2="$(echo $path2 | sed -r 's/\/Dev\//\/Stable\//g')"
path2="$(echo $path2 | sed -r 's/\/Main\//\/Releases\/2.6\/2.6.x\//g')"

cd $path2
