#!/bin/bash
#
# Script that is used to copy an SQL file to the DBUpdate repository.
#

# Variables
file="$(realpath $1)"
dev=false
stable=false

# Error checks
if [[ ! -f $file ]]; then
	echo "Not a file..."
	exit 1
fi
if [[ ! "$file" =~ \.sql$ ]]; then
	echo "Not an SQL file..."
	exit 1
fi

# Full dbupdate checkout out or partial?
if [[ -d $HOME/Projects/DBUpdate/Main ]]; then
    fullcheckout=/Main/Repository
fi

# Check which branch(es) to push to
if [[ $file == *"/Dev/"* ]] || [[ $file == *"/Main/"* ]]; then
	dev=true
elif [[ $file == *"/Stable/"* ]] || [[ $file == *"/Releases/2.6/2.6.x/"* ]]; then
	stable=true
elif [[ $file == *"/Viskan/Kod/"* ]]; then
	dev=true
	stable=true
else
	echo "Not a proper ETM code tree..."
	exit 1
fi

type=StoredProcedures
parent=`dirname $file`
parent=`basename $parent`

shopt -s nocasematch
if [[ "$parent" =~ "tables" ]]; then
    type=Structure
fi

if [[ "$parent" =~ "(reports|develop)" ]]; then
    type=Scripts
fi

# Copy the file to ETM Development
if $dev; then
	cp $file "$HOME/Projects/DBUpdate$fullcheckout/Ramos Main/$type/$(basename $file)"
fi

# Copy the file to ETM Stable
if $stable; then
	cp $file "$HOME/Projects/DBUpdate$fullcheckout/Ramos 2.6/$type/$(basename $file)"
fi

svn status $HOME/Projects/DBUpdate$fullcheckout

